### PR TITLE
Move profiles to dotty

### PR DESCRIPTION
**Pull request by liufengyun**
- Move profiles to dotty
- Make error logs available

### CODE REVIEW

**Comment by liufengyun** [comment]
This PR depends on https://github.com/lampepfl/dotty/pull/12251

**Comment by nicolasstucki** [comment]
CI is failing

**Comment by liufengyun** [comment]
> CI is failing

Yes, once we merge https://github.com/lampepfl/dotty/pull/12251, it will be green.

**Comment by liufengyun** [comment]
CI is green, merging.

**Pull request merged**
