### PR TITLE
Switch to Plot.ly

### PR DESCRIPTION
**Pull request by liufengyun**
Switch to Plotly

Demo: https://liufengyun.github.io/bench/

Changes:

- The time mode is discarded, data are only shown in commit mode (the two buttons in the original right sidebar)
- Plotly is a little slow compared to Chart.js
- Nice zoom feature

TODOs

- [x] remove time mode, use commit mode instead
    - seems difficult to implement due to https://github.com/plotly/plotly.js/issues/1812
    - with a customized clone: https://github.com/liufengyun/plotly.js/commit/b3cb1f2e8de2cfb273eff356ff8fecbde1a080ea
- [x] don't fix Y-axis range
- [x] show moving average
- [x] show datetime in X-axis
- [x] click goes to PR
- [x] show PR + commit hash on hover

### CODE REVIEW

**Comment by liufengyun** [comment]
One idea to fix the performance issue with plot.ly is to only use both Chart.js and Plot.ly.

By default, the charts are displayed using Chart.js. When user clicks `show all points`, we draw the points with Plot.ly.

**Comment by smarter** [comment]
Exciting! I tried the demo but it doesn't seem to work for me, both on Firefox and Chrome the graphs do not load and I have errors like this in the console:
```
Uncaught RangeError: Invalid time value
    at Date.toISOString (<anonymous>)
    at process (main.js:4)
    at Array.map (<anonymous>)
    at prepareData (main.js:205)
    at Object.success (main.js:200)
    at i (jquery-2.2.3.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-2.2.3.min.js:2)
    at z (jquery-2.2.3.min.js:4)
    at XMLHttpRequest.<anonymous> (jquery-2.2.3.min.js:4)
```

**Comment by liufengyun** [comment]
@smarter The error is just fixed and pushed. Refresh your browser, it should work now (clear the cache?).

**Comment by smarter** [comment]
Thanks, it works now! I've only had a quick look so far but my main feedback is that i'd like to see clear points in the graph at every commit (at least when zoomed in enough), in fact I think it might be fine to just have points without tracing a line through them. We don't have to do the exact same things, but for comparison here's the sort of graphs used for firefox: https://treeherder.mozilla.org/perf.html#/graphs?timerange=1209600&series=autoland,2056510,1,1

**Comment by smarter** [comment]
Oh, i just realized that I could click on "median" in the legend to see points! I think that should be the default, but with the interpolated line between the point hidden because it doesn't seem to be very useful

**Comment by leeoniya** [comment]
shameless plug: https://github.com/leeoniya/uPlot#performance

also, careful with webgl/plotly if you need to show a lot of charts:
https://bugs.chromium.org/p/chromium/issues/detail?id=771792

**Comment by liufengyun** [comment]
Thanks for the pointer, @leeoniya, uPlot is impressive. I'll keep it in mind when dealing with the performance issue.

**Comment by liufengyun** [comment]
> Oh, I just realized that I could click on "median" in the legend to see points! I think that should be the default, but with the interpolated line between the point hidden because it doesn't seem to be very useful

I played with it, the problem is that the page does not scroll smoothly with dotted lines in all charts. I'll investigate more about the performance problem.

BTW, the last two points of the moving average is NOT averaged.

**Comment by liufengyun** [comment]
> Oh, i just realized that I could click on "median" in the legend to see points! I think that should be the default, but with the interpolated line between the point hidden because it doesn't seem to be very useful

As a compromise, now we show the point for Dotty by default, but for other tests we show the moving average by default. WDYT?

**Comment by leeoniya** [comment]
you might also be interested in a very similar per-commit perf regressions chart page i have PRed into Rust to replace https://perf.rust-lang.org/:

https://github.com/rust-lang/rustc-perf/issues/742
https://github.com/rust-lang/rustc-perf/pull/744

could be possible to lift that code mostly as-is and tweak for your data format.

**Comment by smarter** [comment]
> I played with it, the problem is that the page does not scroll smoothly with dotted lines in all charts. I'll investigate more about the performance problem.

Is the problem that there's too many points to display? If so, could we default to only loading and displaying points for the last ~30 days for example (and have a dropdown to change the number of points loaded like in https://treeherder.mozilla.org/perf.html#/graphs?timerange=1209600&series=autoland,2056510,1,1)

**Comment by liufengyun** [comment]
> > I played with it, the problem is that the page does not scroll smoothly with dotted lines in all charts. I'll investigate more about the performance problem.
> 
> Is the problem that there's too many points to display? If so, could we default to only loading and displaying points for the last ~30 days for example (and have a dropdown to change the number of points loaded like in https://treeherder.mozilla.org/perf.html#/graphs?timerange=1209600&series=autoland,2056510,1,1)

I tried to show only the last 100 points by default, it still causes problems in scrolling. 

Using a drop-down seems to be at odds with the internal zoom/pan mechanism of Plot.ly, which is more flexible.

**Comment by liufengyun** [comment]
> you might also be interested in a very similar per-commit perf regressions chart page i have PRed into Rust to replace https://perf.rust-lang.org/:
> 
> [rust-lang/rustc-perf#742](https://github.com/rust-lang/rustc-perf/issues/742)
> [rust-lang/rustc-perf#744](https://github.com/rust-lang/rustc-perf/pull/744)
> 
> could be possible to lift that code mostly as-is and tweak for your data format.

Thanks @leeoniya . The performance side is impressive. For our current use case, the main motivation is to have friendly zoom/pan features. That said, we may try uPlot later when the priority/requirement changes.

**Comment by liufengyun** [comment]
One caveat with abandoning the _time mode_ is that we will not be able to put two different lines in one chart, as that does not make much sense.

The best we can do is to align points by commit hash, but we may test the same hash multiple times, e.g. in an open PR.

**Comment by liufengyun** [comment]
Another pitfall I fall into every time I work on the UI is: the points are ordered by _merged time_, not _test time_. Otherwise, we will not be able to understand some jumps in the line.

Ordering by merge time may cause some surprise in reading the points: two neighboring points may only differ in 1 or 2 minutes. Again, the time is the _merge time_, not _test time_, thus it makes sense.

The `fake` merge time for open PRs is the time it's tested, i.e. when we actually do the merge with master in benchmarking.

**Comment by liufengyun** [comment]
The CI failed due to time out. I'm merging and deploying now, but feedback & improvements will continue.

**Pull request merged**
