### PR TITLE
Fix #217: fix syntax for zero tuple

### LINKED ISSUE #217: test tuple22-creation-cons failed for 9049
Please check the log file for more details: http://lamppc37.epfl.ch:8000/pr-9049-b301e4c.out

### PR DESCRIPTION
**Pull request by liufengyun**
Fix #217: fix syntax for zero tuple

### CODE REVIEW

**Comment by nicolasstucki** [comment]
Can we make this a submodule of the dotty project and have compilation tests on all these files? This way we will know beforehand when we will break the benchmarks.

**Comment by nicolasstucki** [comment]
Or even better. Have these files defined as tests in dotty itself and then fetch the least version from the benchmarks

**Comment by liufengyun** [comment]
> Or even better. Have these files defined as tests in dotty itself and then fetch the least version from the benchmarks

Yes, we already have many tests like that, we can make the tuple tests the same too.

**Comment by liufengyun** [comment]
Merge this first to avoid errors.

Will make another PR when the following is merged:

https://github.com/lampepfl/dotty/pull/9136

**Pull request merged**
